// src/features/navbar/Navbar.jsx
import { Link, useNavigate } from "react-router-dom";
import userService from "../../app/services/userService.js";
import { useState, useEffect } from "react";
import ExportModal from "../../shared/components/ExportModal/ExportModal.jsx";
import "./navbar.css";

export default function Navbar() {
  const [user, setUser] = useState(null);
  const [menuOpen, setMenuOpen] = useState(false);
  const [isExportOpen, setIsExportOpen] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    setUser(userService.getCurrentUser());
  }, []);

  const handleLogout = () => {
    userService.logout();
    setUser(null);
    navigate("/login");
    setMenuOpen(false);
  };

  const toggleMenu = () => setMenuOpen(!menuOpen);

  return (
    <>
      <nav className="navbar">
        <div className="navbar-left">
          <Link to="/" className="navbar-brand">
            Task Manager
          </Link>
          <Link to="/upcoming" className="navbar-upcoming-link">
            Nadcházející
          </Link>
        </div>

        <div className={`navbar-right ${menuOpen ? "open" : ""}`}>
          {user ? (
            <>
              <span className="navbar-user">{user.username}</span>
              <button
                className="navbar-export-btn"
                onClick={() => setIsExportOpen(true)}
              >
                <i className="fa-solid fa-download"></i>
              </button>
              <button className="navbar-logout" onClick={handleLogout}>
                Odhlásit se
              </button>
            </>
          ) : (
            <Link
              to="/login"
              className="navbar-login"
              onClick={() => setMenuOpen(false)}
            >
              Přihlášení
            </Link>
          )}
        </div>

        <button className="navbar-hamburger" onClick={toggleMenu}>
          <span className="hamburger-line"></span>
          <span className="hamburger-line"></span>
          <span className="hamburger-line"></span>
        </button>
      </nav>
      <ExportModal
        isOpen={isExportOpen}
        onClose={() => setIsExportOpen(false)}
      />
    </>
  );
}

// bp-angular-app/src/app/pages/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { UserService } from '../../services/user.service';
import { ExportModalComponent } from '../../shared/export-modal/export-modal.component';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterLink, ExportModalComponent],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css',
})
export class NavbarComponent implements OnInit {
  user: any = null;
  menuOpen = false;
  isExportOpen = false;

  constructor(private userService: UserService, private router: Router) {}

  ngOnInit(): void { this.user = this.userService.getCurrentUser(); }

  handleLogout() {
    this.userService.logout();
    this.user = null;
    this.menuOpen = false;
    this.router.navigate(['/login']);
  }
}

<nav class="navbar">
  <div class="navbar-left">
    <a routerLink="/" class="navbar-brand">Task Manager</a>
    <a routerLink="/upcoming" class="navbar-upcoming-link">Nadcházející</a>
  </div>
  <div class="navbar-right" [class.open]="menuOpen">
    @if (user) {
      <span class="navbar-user">{{ user.username }}</span>
      <button class="navbar-export-btn" (click)="isExportOpen = true"><i class="fa-solid fa-download"></i></button>
      <button class="navbar-logout" (click)="handleLogout()">Odhlásit se</button>
    } @else {
      <a routerLink="/login" class="navbar-login" (click)="menuOpen = false">Přihlášení</a>
    }
  </div>
  <button class="navbar-hamburger" (click)="menuOpen = !menuOpen">
    <span class="hamburger-line"></span><span class="hamburger-line"></span><span class="hamburger-line"></span>
  </button>
</nav>
<app-export-modal [isOpen]="isExportOpen" (closed)="isExportOpen = false"></app-export-modal>
