// bp-angular-app/src/app/pages/dashboard/dashboard.component.ts
import { Component, Input } from '@angular/core';
import { TaskService } from '../../services/task.service';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.css',
})
export class DashboardComponent {
  @Input() projects: any[] = [];
  constructor(private taskService: TaskService) {}
  get tasks() { return this.taskService.getTasks(); }
  countByStatus(status: string) { return this.tasks.filter((t) => t.status === status).length; }
  countByPriority(priority: string) { return this.tasks.filter((t) => t.priority === priority).length; }
  get dueSoonCount() { return this.tasks.filter((t) => t.dueDate && ((new Date(t.dueDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24) >= 0) && ((new Date(t.dueDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24) <= 1)).length; }
}

<div class="db-container">
  <div class="db-stats-grid">
    <div class="db-stat-box"><h3>Projekty celkem</h3><p>{{ projects.length }}</p></div>
    <div class="db-stat-box"><h3>Úkoly celkem</h3><p>{{ tasks.length }}</p></div>
    <div class="db-stat-box"><h3>Úkoly podle stavu</h3><p>TODO: {{ countByStatus('TODO') }}</p><p>In Progress: {{ countByStatus('IN_PROGRESS') }}</p><p>Done: {{ countByStatus('DONE') }}</p></div>
    <div class="db-stat-box"><h3>Úkoly podle priority</h3><p>Low: {{ countByPriority('LOW') }}</p><p>Medium: {{ countByPriority('MEDIUM') }}</p><p>High: {{ countByPriority('HIGH') }}</p></div>
    <div class="db-stat-box"><h3>Úkoly s termínem do 1 dne</h3><p>{{ dueSoonCount }}</p></div>
  </div>
</div>

// src/features/dashboard/Dashboard.jsx
import taskService from "../../app/services/task.service";
import "./dashboard.css";

export default function Dashboard({ projects }) {
  const tasks = taskService.getTasks();

  const totalProjects = projects.length;
  const totalTasks = tasks.length;

  const tasksByStatus = {
    TODO: tasks.filter((t) => t.status === "TODO").length,
    IN_PROGRESS: tasks.filter((t) => t.status === "IN_PROGRESS").length,
    DONE: tasks.filter((t) => t.status === "DONE").length,
  };

  const tasksByPriority = {
    LOW: tasks.filter((t) => t.priority === "LOW").length,
    MEDIUM: tasks.filter((t) => t.priority === "MEDIUM").length,
    HIGH: tasks.filter((t) => t.priority === "HIGH").length,
  };

  const tasksDueSoon = tasks.filter((t) => {
    if (!t.dueDate) return false;
    const now = new Date();
    const due = new Date(t.dueDate);
    const diff = (due - now) / (1000 * 60 * 60 * 24);
    return diff >= 0 && diff <= 1;
  }).length;

  return (
    <div className="db-container">
      <div className="db-stats-grid">
        <div className="db-stat-box">
          <h3>Projekty celkem</h3>
          <p>{totalProjects}</p>
        </div>
        <div className="db-stat-box">
          <h3>Úkoly celkem</h3>
          <p>{totalTasks}</p>
        </div>
        <div className="db-stat-box">
          <h3>Úkoly podle stavu</h3>
          <p>TODO: {tasksByStatus.TODO}</p>
          <p>In Progress: {tasksByStatus.IN_PROGRESS}</p>
          <p>Done: {tasksByStatus.DONE}</p>
        </div>
        <div className="db-stat-box">
          <h3>Úkoly podle priority</h3>
          <p>Low: {tasksByPriority.LOW}</p>
          <p>Medium: {tasksByPriority.MEDIUM}</p>
          <p>High: {tasksByPriority.HIGH}</p>
        </div>
        <div className="db-stat-box">
          <h3>Úkoly s termínem do 1 dne</h3>
          <p>{tasksDueSoon}</p>
        </div>
      </div>
    </div>
  );
}
