// bp-angular-app/src/app/pages/upcoming/upcoming.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ProjectService } from '../../services/project.service';
import { TaskService } from '../../services/task.service';

@Component({
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './upcoming.component.html',
  styleUrl: './upcoming.component.css',
})
export class UpcomingComponent implements OnInit {
  Object = Object;
  upcomingTasks: Record<string, any[]> = {};
  constructor(private projectService: ProjectService, private taskService: TaskService) {}
  ngOnInit() { const projects = this.projectService.getProjects(); const tasks = this.taskService.getTasks(); const today = new Date(); for (let i = 0; i <= 90; i++) { const day = new Date(); day.setDate(today.getDate() + i); const key = `${day.getFullYear()}-${String(day.getMonth() + 1).padStart(2, '0')}-${String(day.getDate()).padStart(2, '0')}`; this.upcomingTasks[key] = tasks.filter((task) => task.dueDate === key).map((task) => { const project = projects.find((p) => p.id === task.projectId); return { ...task, projectName: project ? project.name : 'Bez projektu', projectId: project ? project.id : null }; }).sort((a, b) => (a.projectName < b.projectName ? -1 : a.projectName > b.projectName ? 1 : 0)); } }
  formatDate(dateString: string) { return new Date(dateString).toLocaleDateString('cs-CZ', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }); }
}

<div class="upcoming-container">
  <h2>Nadcházející úkoly</h2>
  @for (date of Object.keys(upcomingTasks); track date) {
    <div class="day-block" [class.has-tasks]="upcomingTasks[date].length > 0">
      <h3>{{ formatDate(date) }}</h3>
      @if (upcomingTasks[date].length > 0) {
        <ul>
          @for (task of upcomingTasks[date]; track task.id) {
            <li><a class="task-link" [routerLink]="task.projectId ? ['/projects', task.projectId] : ['/']"><span class="task-project">[{{ task.projectName }}]</span> <span class="task-title">{{ task.title }}</span></a></li>
          }
        </ul>
      } @else { <p class="no-tasks">Žádné úkoly</p> }
    </div>
  }
</div>

// src/features/upcoming/Upcoming.jsx
import { useState, useEffect } from "react";
import { Link } from "react-router-dom";
import taskService from "../../app/services/task.service.js";
import projectService from "../../app/services/project.service.js";
import "./upcoming.css";

export default function Upcoming() {
  const [upcomingTasks, setUpcomingTasks] = useState({});

  const formatLocalDate = (date) => {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    return `${year}-${month}-${day}`;
  };

  useEffect(() => {
    const projects = projectService.getProjects();
    const tasks = taskService.getTasks();

    const daysAhead = 90; // 3 měsíce
    const today = new Date();
    const upcoming = {};

    for (let i = 0; i <= daysAhead; i++) {
      const day = new Date();
      day.setDate(today.getDate() + i);

      const key = formatLocalDate(day);

      let tasksForDay = tasks
        .filter((task) => task.dueDate === key)
        .map((task) => {
          const project = projects.find((p) => p.id === task.projectId);
          return {
            ...task,
            projectName: project ? project.name : "Bez projektu",
            projectGradient: project ? project.gradient : null,
            projectId: project ? project.id : null,
          };
        });

      // Seřadíme podle projectName
      tasksForDay.sort((a, b) => {
        if (a.projectName < b.projectName) return -1;
        if (a.projectName > b.projectName) return 1;
        return 0;
      });

      upcoming[key] = tasksForDay;
    }

    setUpcomingTasks(upcoming);
  }, []);

  const formatDate = (dateString) => {
    const options = {
      weekday: "long",
      day: "numeric",
      month: "long",
      year: "numeric",
    };
    return new Date(dateString).toLocaleDateString("cs-CZ", options);
  };

  return (
    <div className="upcoming-container">
      <h2>Nadcházející úkoly</h2>

      {Object.keys(upcomingTasks).map((date) => (
        <div
          key={date}
          className={`day-block ${upcomingTasks[date].length > 0 ? "has-tasks" : ""}`}
        >
          <h3>{formatDate(date)}</h3>

          {upcomingTasks[date].length > 0 ? (
            <ul>
              {upcomingTasks[date].map((task) => (
                <li key={task.id}>
                  <Link
                    to={task.projectId ? `/projects/${task.projectId}` : "#"}
                    className="task-link"
                  >
                    <span className="task-project">[{task.projectName}]</span>{" "}
                    <span className="task-title">{task.title}</span>
                  </Link>
                </li>
              ))}
            </ul>
          ) : (
            <p className="no-tasks">Žádné úkoly</p>
          )}
        </div>
      ))}
    </div>
  );
}
