// bp-angular-app/src/app/pages/project-detail/project-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { ProjectService } from '../../services/project.service';
import { TaskService } from '../../services/task.service';
import { TaskPriority, TaskStatus } from '../../constants/task.constants';

@Component({
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './project-detail.component.html',
  styleUrl: './project-detail.component.css',
})
export class ProjectDetailComponent implements OnInit {
  projectId = 0;
  project: any = null;
  tasks: any[] = [];
  formVisible = false;
  newTask: any = { title: '', description: '', status: TaskStatus.TODO, priority: TaskPriority.MEDIUM, dueDate: '' };
  editingTaskId: number | null = null;
  editingTask: any = {};
  editingDesc = false;
  descValue = '';
  statusFilter = '';
  priorityFilter = '';
  dueSoonOnly = false;
  statusValues = Object.values(TaskStatus);
  priorityValues = Object.values(TaskPriority);
  statusCz: any = { TODO: 'Zpracovat', IN_PROGRESS: 'Probíhá', DONE: 'Hotovo' };
  priorityCz: any = { LOW: 'Nízká', MEDIUM: 'Střední', HIGH: 'Vysoká' };

  constructor(private route: ActivatedRoute, public router: Router, private projectService: ProjectService, private taskService: TaskService) {}

  ngOnInit() {
    this.projectId = Number(this.route.snapshot.paramMap.get('id'));
    this.project = this.projectService.getProjectById(this.projectId);
    this.tasks = this.taskService.getTasksByProjectId(this.projectId);
    this.descValue = this.project?.description || '';
  }

  refreshTasks() { this.tasks = this.taskService.getTasksByProjectId(this.projectId); }
  createTask(event: Event) { event.preventDefault(); if (!this.newTask.title.trim()) return; this.taskService.createTask({ ...this.newTask, projectId: this.projectId }); this.refreshTasks(); this.formVisible = false; this.newTask = { title: '', description: '', status: TaskStatus.TODO, priority: TaskPriority.MEDIUM, dueDate: '' }; }
  deleteTask(id: number) { const task = this.tasks.find((t) => t.id === id); if (task && window.confirm(`Opravdu chcete smazat úkol "${task.title}"? Tuto akci nelze vrátit.`)) { this.taskService.deleteTask(id); this.refreshTasks(); } }
  startEdit(task: any) { this.editingTaskId = task.id; this.editingTask = { ...task }; }
  saveTaskEdit() { if (!this.editingTask.title.trim()) return; this.taskService.updateTask(this.editingTask); this.editingTaskId = null; this.editingTask = {}; this.refreshTasks(); }
  saveProjectDesc() { this.projectService.updateProject({ ...this.project, description: this.descValue }); this.project = { ...this.project, description: this.descValue }; this.editingDesc = false; }

  get filteredTasks() {
    return this.tasks.filter((t) => {
      if (this.statusFilter && t.status !== this.statusFilter) return false;
      if (this.priorityFilter && t.priority !== this.priorityFilter) return false;
      if (this.dueSoonOnly) { if (!t.dueDate) return false; const diff = (new Date(t.dueDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24); if (diff < 0 || diff > 1) return false; }
      return true;
    });
  }
}

@if (!project) {
  <div class="project-detail-container"><h2>Projekt nebyl nalezen</h2><button class="back-btn" (click)="router.navigate(['/'])">Zpět na projekty</button></div>
} @else {
  <div class="project-detail-container">
    <button class="back-btn" (click)="router.navigate(['/'])">← Zpět</button>
    <div class="project-header" [style.background]="project.gradient">
      <h1 class="project-header-title">{{ project.name }}</h1>
      @if (editingDesc) {
        <div class="project-desc-edit-wrap">
          <textarea class="project-desc-input" [(ngModel)]="descValue"></textarea>
          <div class="project-desc-buttons"><button class="task-save-btn" (click)="saveProjectDesc()">Uložit</button><button class="task-delete-button" (click)="editingDesc = false">Zrušit</button></div>
        </div>
      } @else {
        <p class="project-header-desc">{{ project.description || 'Bez popisu' }} <i class="fa-solid fa-pen-to-square edit-desc-icon" (click)="editingDesc = true"></i></p>
      }
      <span class="project-header-date">Datum vytvoření: {{ project.createdAt | date }}</span>
    </div>

    <div class="tasks-section">
      <div class="tasks-header"><h2 class="tasks-title">Úkoly</h2><button class="task-button" (click)="formVisible = !formVisible">{{ formVisible ? 'Zavřít' : 'Přidat úkol' }}</button></div>
      @if (formVisible) {
        <form class="task-form" (submit)="createTask($event)">
          <input type="text" placeholder="Název úkolu" [(ngModel)]="newTask.title" name="title" required />
          <textarea placeholder="Popis" [(ngModel)]="newTask.description" name="description"></textarea>
          <select [(ngModel)]="newTask.status" name="status">@for (s of statusValues; track s) {<option [value]="s">{{ statusCz[s] }}</option>}</select>
          <select [(ngModel)]="newTask.priority" name="priority">@for (p of priorityValues; track p) {<option [value]="p">{{ priorityCz[p] }}</option>}</select>
          <input type="date" [(ngModel)]="newTask.dueDate" name="dueDate" required />
          <button class="task-save-btn" type="submit">Uložit</button>
        </form>
      }

      <div class="task-filters">
        <select [(ngModel)]="statusFilter" name="statusFilter"><option value="">Všechny stavy</option>@for (s of statusValues; track s) {<option [value]="s">{{ statusCz[s] }}</option>}</select>
        <select [(ngModel)]="priorityFilter" name="priorityFilter"><option value="">Všechny priority</option>@for (p of priorityValues; track p) {<option [value]="p">{{ priorityCz[p] }}</option>}</select>
        <label class="due-soon-label"><input type="checkbox" [(ngModel)]="dueSoonOnly" name="dueSoonOnly" />Úkoly do 1 dne</label>
      </div>

      <div class="task-grid">
        @for (task of filteredTasks; track task.id) {
          <div class="task-card"><div class="task-inner-card">
            @if (editingTaskId === task.id) {
              <input class="task-card-title-input" [(ngModel)]="editingTask.title" name="etitle{{task.id}}" />
              <textarea class="task-card-desc-input" [(ngModel)]="editingTask.description" name="edesc{{task.id}}"></textarea>
              <select [(ngModel)]="editingTask.status" name="estatus{{task.id}}">@for (s of statusValues; track s) {<option [value]="s">{{ statusCz[s] }}</option>}</select>
              <select [(ngModel)]="editingTask.priority" name="epriority{{task.id}}">@for (p of priorityValues; track p) {<option [value]="p">{{ priorityCz[p] }}</option>}</select>
              <input type="date" [(ngModel)]="editingTask.dueDate" name="edue{{task.id}}" />
            } @else {
              <h3 class="task-card-title">{{ task.title }}</h3><p class="task-card-desc">{{ task.description }}</p><p class="task-card-status">Status: {{ statusCz[task.status] }}</p><p class="task-card-priority">Priorita: {{ priorityCz[task.priority] }}</p>
              @if (task.dueDate) {<p class="task-card-enddate">Termín dokončení: {{ task.dueDate }}</p>}
            }
          </div>
          <div class="task-card-buttons">
            @if (editingTaskId === task.id) { <button class="task-save-btn" (click)="saveTaskEdit()">Uložit změny</button> }
            @else { <button class="task-button task-edit-btn" (click)="startEdit(task)">Upravit</button><button class="task-delete-button" (click)="deleteTask(task.id)">Smazat</button> }
          </div></div>
        }
      </div>
    </div>
  </div>
}

// src/features/projects/ProjectDetail.jsx
import { useParams, useNavigate } from "react-router-dom";
import { useEffect, useState } from "react";
import projectService from "../../app/services/project.service";
import taskService from "../../app/services/task.service";
import {
  TaskStatus,
  TaskPriority,
} from "../../shared/constants/task.constants";
import {
  MAX_TASK_TITLE_LENGTH,
  MAX_TASK_DESCRIPTION_LENGTH,
  MAX_PROJECT_DESCRIPTION_LENGTH,
} from "../../shared/constants/input.limits";
import "./projectDetail.css";

export default function ProjectDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const projectId = Number(id);

  const [project, setProject] = useState(null);
  const [tasks, setTasks] = useState([]);
  const [formVisible, setFormVisible] = useState(false);
  const [newTask, setNewTask] = useState({
    title: "",
    description: "",
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    dueDate: "",
  });

  const [editingTaskId, setEditingTaskId] = useState(null);
  const [editingTask, setEditingTask] = useState({});
  const [editingDesc, setEditingDesc] = useState(false);
  const [descValue, setDescValue] = useState("");
  const [error, setError] = useState("");

  const [statusFilter, setStatusFilter] = useState("");
  const [priorityFilter, setPriorityFilter] = useState("");
  const [dueSoonOnly, setDueSoonOnly] = useState(false);

  useEffect(() => {
    const found = projectService.getProjectById(projectId);
    setProject(found);
    setTasks(taskService.getTasksByProjectId(projectId));
    setDescValue(found?.description || "");
  }, [projectId]);

  if (!project) {
    return (
      <div className="project-detail-container">
        <h2>Projekt nebyl nalezen</h2>
        <button className="back-btn" onClick={() => navigate("/")}>
          Zpět na projekty
        </button>
      </div>
    );
  }

  const refreshTasks = () => {
    setTasks(taskService.getTasksByProjectId(projectId));
  };

  const handleCreateTask = (e) => {
    e.preventDefault();
    const title = newTask.title.trim();
    const description = newTask.description.trim();

    if (!title) {
      setError("Název úkolu nesmí být prázdný.");
      return;
    }
    if (title.length > MAX_TASK_TITLE_LENGTH) {
      setError(
        `Název úkolu může mít maximálně ${MAX_TASK_TITLE_LENGTH} znaků.`,
      );
      return;
    }
    if (description.length > MAX_TASK_DESCRIPTION_LENGTH) {
      setError(
        `Popis úkolu může mít maximálně ${MAX_TASK_DESCRIPTION_LENGTH} znaků.`,
      );
      return;
    }

    try {
      taskService.createTask({ ...newTask, projectId });
      refreshTasks();
      setFormVisible(false);
      setNewTask({
        title: "",
        description: "",
        status: TaskStatus.TODO,
        priority: TaskPriority.MEDIUM,
        dueDate: "",
      });
      setError("");
    } catch (err) {
      setError(err.message);
    }
  };

  const handleDelete = (taskId) => {
    const task = tasks.find((t) => t.id === taskId);
    if (!task) return;

    const confirmDelete = window.confirm(
      `Opravdu chcete smazat úkol "${task.title}"? Tuto akci nelze vrátit.`,
    );

    if (confirmDelete) {
      taskService.deleteTask(taskId);
      refreshTasks();
    }
  };

  const startEditingTask = (task) => {
    setEditingTaskId(task.id);
    setEditingTask({ ...task });
  };

  const saveTaskEdit = () => {
    const title = editingTask.title.trim();
    const description = (editingTask.description || "").trim();

    if (!title) {
      setError("Název úkolu nesmí být prázdný.");
      return;
    }
    if (title.length > MAX_TASK_TITLE_LENGTH) {
      setError(
        `Název úkolu může mít maximálně ${MAX_TASK_TITLE_LENGTH} znaků.`,
      );
      return;
    }
    if (description.length > MAX_TASK_DESCRIPTION_LENGTH) {
      setError(
        `Popis úkolu může mít maximálně ${MAX_TASK_DESCRIPTION_LENGTH} znaků.`,
      );
      return;
    }

    try {
      taskService.updateTask({
        ...editingTask,
        title,
        description,
      });
      refreshTasks();
      setEditingTaskId(null);
      setEditingTask({});
      setError("");
    } catch (err) {
      setError(err.message);
    }
  };

  const statusCz = {
    [TaskStatus.TODO]: "Zpracovat",
    [TaskStatus.IN_PROGRESS]: "Probíhá",
    [TaskStatus.DONE]: "Hotovo",
  };

  const priorityCz = {
    [TaskPriority.LOW]: "Nízká",
    [TaskPriority.MEDIUM]: "Střední",
    [TaskPriority.HIGH]: "Vysoká",
  };

  const stats = {
    total: tasks.length,
    todo: tasks.filter((t) => t.status === TaskStatus.TODO).length,
    inProgress: tasks.filter((t) => t.status === TaskStatus.IN_PROGRESS).length,
    done: tasks.filter((t) => t.status === TaskStatus.DONE).length,
    high: tasks.filter((t) => t.priority === TaskPriority.HIGH).length,
  };

  const filteredTasks = tasks.filter((t) => {
    if (statusFilter && t.status !== statusFilter) return false;
    if (priorityFilter && t.priority !== priorityFilter) return false;
    if (dueSoonOnly) {
      if (!t.dueDate) return false;
      const now = new Date();
      const due = new Date(t.dueDate);
      const diff = (due - now) / (1000 * 60 * 60 * 24);
      if (diff < 0 || diff > 1) return false;
    }
    return true;
  });

  const saveProjectDesc = () => {
    const description = descValue.trim();

    if (description.length > MAX_PROJECT_DESCRIPTION_LENGTH) {
      setError(
        `Popis projektu může mít maximálně ${MAX_PROJECT_DESCRIPTION_LENGTH} znaků.`,
      );
      return;
    }

    try {
      projectService.updateProject({ ...project, description });
      setProject({ ...project, description });
      setEditingDesc(false);
      setError("");
    } catch (err) {
      setError(err.message);
    }
  };

  const cancelProjectDesc = () => {
    setDescValue(project.description || "");
    setEditingDesc(false);
  };

  return (
    <div className="project-detail-container">
      <button className="back-btn" onClick={() => navigate(-1)}>
        ← Zpět
      </button>

      <div className="project-header" style={{ background: project.gradient }}>
        <h1 className="project-header-title">{project.name}</h1>

        {editingDesc ? (
          <div className="project-desc-edit-wrap">
            <textarea
              className="project-desc-input"
              value={descValue}
              maxLength={MAX_PROJECT_DESCRIPTION_LENGTH}
              onChange={(e) => setDescValue(e.target.value)}
            />
            <div className="project-desc-buttons">
              <button className="task-save-btn" onClick={saveProjectDesc}>
                Uložit
              </button>
              <button
                className="task-delete-button"
                onClick={cancelProjectDesc}
              >
                Zrušit
              </button>
            </div>
          </div>
        ) : (
          <p className="project-header-desc">
            {project.description || "Bez popisu"}{" "}
            <i
              className="fa-solid fa-pen-to-square edit-desc-icon"
              onClick={() => setEditingDesc(true)}
              title="Upravit popis"
            ></i>
          </p>
        )}

        <span className="project-header-date">
          Datum vytvoření: {new Date(project.createdAt).toLocaleDateString()}
        </span>
      </div>

      {error && <p className="project-create-error">{error}</p>}

      <div className="stats-grid">
        <div className="stat-box">
          <h3>{stats.total}</h3>
          <p>Celkem</p>
        </div>
        <div className="stat-box">
          <h3>{stats.todo}</h3>
          <p>TODO</p>
        </div>
        <div className="stat-box">
          <h3>{stats.inProgress}</h3>
          <p>Probíhá</p>
        </div>
        <div className="stat-box">
          <h3>{stats.done}</h3>
          <p>Hotovo</p>
        </div>
        <div className="stat-box">
          <h3>{stats.high}</h3>
          <p>Vysoká priorita</p>
        </div>
      </div>

      <div className="tasks-section">
        <div className="tasks-header">
          <h2 className="tasks-title">Úkoly</h2>
          <button
            className="task-button"
            onClick={() => setFormVisible(!formVisible)}
          >
            {formVisible ? "Zavřít" : "Přidat úkol"}
          </button>
        </div>

        {formVisible && (
          <form className="task-form" onSubmit={handleCreateTask}>
            <input
              type="text"
              placeholder="Název úkolu"
              value={newTask.title}
              maxLength={MAX_TASK_TITLE_LENGTH}
              onChange={(e) =>
                setNewTask({ ...newTask, title: e.target.value })
              }
              required
            />
            <textarea
              placeholder="Popis"
              value={newTask.description}
              maxLength={MAX_TASK_DESCRIPTION_LENGTH}
              onChange={(e) =>
                setNewTask({ ...newTask, description: e.target.value })
              }
            />
            <select
              value={newTask.status}
              onChange={(e) =>
                setNewTask({ ...newTask, status: e.target.value })
              }
            >
              {Object.values(TaskStatus).map((s) => (
                <option key={s} value={s}>
                  {statusCz[s]}
                </option>
              ))}
            </select>
            <select
              value={newTask.priority}
              onChange={(e) =>
                setNewTask({ ...newTask, priority: e.target.value })
              }
            >
              {Object.values(TaskPriority).map((p) => (
                <option key={p} value={p}>
                  {priorityCz[p]}
                </option>
              ))}
            </select>
            <input
              type="date"
              required
              value={newTask.dueDate}
              onChange={(e) =>
                setNewTask({ ...newTask, dueDate: e.target.value })
              }
            />
            <button className="task-save-btn" type="submit">
              Uložit
            </button>
          </form>
        )}

        <div className="task-filters">
          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
          >
            <option value="">Všechny stavy</option>
            {Object.values(TaskStatus).map((s) => (
              <option key={s} value={s}>
                {statusCz[s]}
              </option>
            ))}
          </select>
          <select
            value={priorityFilter}
            onChange={(e) => setPriorityFilter(e.target.value)}
          >
            <option value="">Všechny priority</option>
            {Object.values(TaskPriority).map((p) => (
              <option key={p} value={p}>
                {priorityCz[p]}
              </option>
            ))}
          </select>
          <label className="due-soon-label">
            <input
              type="checkbox"
              checked={dueSoonOnly}
              onChange={() => setDueSoonOnly(!dueSoonOnly)}
            />
            Úkoly do 1 dne
          </label>
        </div>

        <div className="task-grid">
          {filteredTasks.map((task) => {
            const isDueSoon = task.dueDate
              ? (new Date(task.dueDate) - new Date()) / (1000 * 60 * 60 * 24) <=
                1
              : false;

            return (
              <div
                key={task.id}
                className={`task-card ${isDueSoon ? "task-due-soon" : ""}`}
              >
                <div className="task-inner-card">
                  {editingTaskId === task.id ? (
                    <>
                      <input
                        className="task-card-title-input"
                        value={editingTask.title}
                        maxLength={MAX_TASK_TITLE_LENGTH}
                        onChange={(e) =>
                          setEditingTask({
                            ...editingTask,
                            title: e.target.value,
                          })
                        }
                      />
                      <textarea
                        className="task-card-desc-input"
                        value={editingTask.description}
                        maxLength={MAX_TASK_DESCRIPTION_LENGTH}
                        onChange={(e) =>
                          setEditingTask({
                            ...editingTask,
                            description: e.target.value,
                          })
                        }
                      />
                      <select
                        value={editingTask.status}
                        onChange={(e) =>
                          setEditingTask({
                            ...editingTask,
                            status: e.target.value,
                          })
                        }
                      >
                        {Object.values(TaskStatus).map((s) => (
                          <option key={s} value={s}>
                            {statusCz[s]}
                          </option>
                        ))}
                      </select>
                      <select
                        value={editingTask.priority}
                        onChange={(e) =>
                          setEditingTask({
                            ...editingTask,
                            priority: e.target.value,
                          })
                        }
                      >
                        {Object.values(TaskPriority).map((p) => (
                          <option key={p} value={p}>
                            {priorityCz[p]}
                          </option>
                        ))}
                      </select>
                      <input
                        type="date"
                        value={editingTask.dueDate}
                        onChange={(e) =>
                          setEditingTask({
                            ...editingTask,
                            dueDate: e.target.value,
                          })
                        }
                      />
                    </>
                  ) : (
                    <>
                      <h3 className="task-card-title">{task.title}</h3>
                      <p className="task-card-desc">{task.description}</p>
                      <p className="task-card-status">
                        Status: {statusCz[task.status]}
                      </p>
                      <p className="task-card-priority">
                        Priorita: {priorityCz[task.priority]}
                      </p>
                      {task.dueDate && (
                        <p className="task-card-enddate">
                          Termín dokončení:{" "}
                          {new Date(task.dueDate).toLocaleDateString()}
                        </p>
                      )}
                    </>
                  )}
                </div>

                <div className="task-card-buttons">
                  {editingTaskId === task.id ? (
                    <button className="task-save-btn" onClick={saveTaskEdit}>
                      Uložit změny
                    </button>
                  ) : (
                    <>
                      <button
                        className="task-button task-edit-btn"
                        onClick={() => startEditingTask(task)}
                      >
                        Upravit
                      </button>
                      <button
                        className="task-delete-button"
                        onClick={() => handleDelete(task.id)}
                      >
                        Smazat
                      </button>
                    </>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
