// src/features/users/Register.jsx
import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import userService from "../../app/services/userService.js";
import "./auth.css";

export default function Register() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");

  const navigate = useNavigate();

  const handleRegister = (e) => {
    e.preventDefault();

    try {
      userService.register({ username, password });
      navigate("/");
      location.reload();
    } catch (err) {
      setError(err.message);
    }
  };

  return (
    <div className="auth-container">
      <h2>Registrace</h2>
      <form onSubmit={handleRegister} className="auth-form">
        <input
          type="text"
          placeholder="Uživatelské jméno"
          value={username}
          onChange={(e) => setUsername(e.target.value)}
          required
        />
        <input
          type="password"
          placeholder="Heslo"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
        />
        <button type="submit">Zaregistrovat se</button>
        {error && <p className="auth-error">{error}</p>}
      </form>
      <p className="no-account-text">
        Již máte účet? <Link to="/login">Přihlásit se</Link>
      </p>
    </div>
  );
}

// bp-angular-app/src/app/pages/register/register.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { UserService } from '../../services/user.service';

@Component({
  standalone: true,
  imports: [FormsModule, RouterLink],
  templateUrl: './register.component.html',
  styleUrl: './register.component.css',
})
export class RegisterComponent {
  username = '';
  password = '';
  error = '';
  constructor(private userService: UserService, private router: Router) {}

  handleRegister(event: Event) {
    event.preventDefault();
    try {
      this.userService.register({ username: this.username, password: this.password });
      this.router.navigate(['/']).then(() => window.location.reload());
    } catch (err: any) { this.error = err.message; }
  }
}

<div class="auth-container">
  <h2>Registrace</h2>
  <form class="auth-form" (submit)="handleRegister($event)">
    <input type="text" placeholder="Uživatelské jméno" [(ngModel)]="username" name="username" required />
    <input type="password" placeholder="Heslo" [(ngModel)]="password" name="password" required />
    <button type="submit">Zaregistrovat se</button>
    @if (error) { <p class="auth-error">{{ error }}</p> }
  </form>
  <p class="no-account-text">Již máte účet? <a routerLink="/login">Přihlásit se</a></p>
</div>
