// bp-angular-app/src/app/shared/export-modal/export-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { exportData } from '../../utils/export/export-data';
import { UserService } from '../../services/user.service';

@Component({
  selector: 'app-export-modal',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './export-modal.component.html',
  styleUrl: './export-modal.component.css',
})
export class ExportModalComponent {
  @Input() isOpen = false;
  @Output() closed = new EventEmitter<void>();

  includeProjects = true;
  includeTasks = true;
  includeUser = false;
  format = 'json';
  warning = '';

  constructor(private userService: UserService) {}

  handleExport() {
    if (!this.includeProjects && !this.includeTasks && !this.includeUser) {
      this.warning = 'Musíte zvolit alespoň jednu možnost pro export.';
      setTimeout(() => (this.warning = ''), 5000);
      return;
    }
    exportData({
      includeProjects: this.includeProjects,
      includeTasks: this.includeTasks,
      includeUser: this.includeUser,
      format: this.format,
    }, this.userService);
    this.closed.emit();
  }
}

@if (isOpen) {
  <div class="export-overlay" (click)="closed.emit()">
    <div class="export-modal" (click)="$event.stopPropagation()">
      <h2>Data pro export</h2>
      @if (warning) { <div class="export-warning">{{ warning }}</div> }
      <div class="export-section">
        <h3>Co exportovat</h3>
        <label class="export-option"><input type="checkbox" [(ngModel)]="includeProjects" />Projekty</label>
        <label class="export-option"><input type="checkbox" [(ngModel)]="includeTasks" />Úkoly</label>
        <label class="export-option"><input type="checkbox" [(ngModel)]="includeUser" />Uživatelské informace</label>
      </div>
      <div class="export-section">
        <h3>Formát</h3>
        <label class="export-option"><input type="radio" name="format" value="json" [(ngModel)]="format" />JSON</label>
        <label class="export-option"><input type="radio" name="format" value="csv" [(ngModel)]="format" />CSV</label>
        <label class="export-option"><input type="radio" name="format" value="md" [(ngModel)]="format" />Markdown</label>
      </div>
      <div class="export-buttons">
        <button class="export-btn export-btn-secondary" (click)="closed.emit()">Zrušit</button>
        <button class="export-btn export-btn-primary" (click)="handleExport()">Exportovat</button>
      </div>
    </div>
  </div>
}

// src/shared/components/ExportModal/ExportModal.jsx
import { useState, useEffect } from "react";
import { exportData } from "../../utils/export/exportData.js";
import "./exportmodal.css";

export default function ExportModal({ isOpen, onClose }) {
  const [includeProjects, setIncludeProjects] = useState(true);
  const [includeTasks, setIncludeTasks] = useState(true);
  const [includeUser, setIncludeUser] = useState(false);
  const [format, setFormat] = useState("json");
  const [warning, setWarning] = useState("");

  useEffect(() => {
    if (!warning) return;
    const timer = setTimeout(() => setWarning(""), 5000);
    return () => clearTimeout(timer);
  }, [warning]);

  const handleExport = () => {
    if (!includeProjects && !includeTasks && !includeUser) {
      setWarning("Musíte zvolit alespoň jednu možnost pro export.");
      return;
    }

    exportData({
      includeProjects,
      includeTasks,
      includeUser,
      format,
    });

    onClose();
  };

  return (
    <>
      {isOpen && (
        <div className="export-overlay" onClick={onClose}>
          <div className="export-modal" onClick={(e) => e.stopPropagation()}>
            <h2>Data pro export</h2>

            {warning && <div className="export-warning">{warning}</div>}

            <div className="export-section">
              <h3>Co exportovat</h3>

              <label className="export-option">
                <input
                  type="checkbox"
                  checked={includeProjects}
                  onChange={(e) => setIncludeProjects(e.target.checked)}
                />
                Projekty
              </label>

              <label className="export-option">
                <input
                  type="checkbox"
                  checked={includeTasks}
                  onChange={(e) => setIncludeTasks(e.target.checked)}
                />
                Úkoly
              </label>

              <label className="export-option">
                <input
                  type="checkbox"
                  checked={includeUser}
                  onChange={(e) => setIncludeUser(e.target.checked)}
                />
                Uživatelské informace
              </label>
            </div>

            <div className="export-section">
              <h3>Formát</h3>

              <label className="export-option">
                <input
                  type="radio"
                  value="json"
                  checked={format === "json"}
                  onChange={(e) => setFormat(e.target.value)}
                />
                JSON
              </label>

              <label className="export-option">
                <input
                  type="radio"
                  value="csv"
                  checked={format === "csv"}
                  onChange={(e) => setFormat(e.target.value)}
                />
                CSV
              </label>

              <label className="export-option">
                <input
                  type="radio"
                  value="md"
                  checked={format === "md"}
                  onChange={(e) => setFormat(e.target.value)}
                />
                Markdown
              </label>
            </div>

            <div className="export-buttons">
              <button
                className="export-btn export-btn-secondary"
                onClick={onClose}
              >
                Zrušit
              </button>

              <button
                className="export-btn export-btn-primary"
                onClick={handleExport}
              >
                Exportovat
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
