// bp-angular-app/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { UserService } from '../../services/user.service';

@Component({
  standalone: true,
  imports: [FormsModule, RouterLink],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css',
})
export class LoginComponent {
  username = '';
  password = '';
  error = '';
  constructor(private userService: UserService, private router: Router) {}

  handleLogin(event: Event) {
    event.preventDefault();
    try {
      this.userService.login({ username: this.username, password: this.password });
      this.router.navigate(['/']).then(() => window.location.reload());
    } catch (err: any) { this.error = err.message; }
  }
}

<div class="auth-container">
  <h2>Přihlášení</h2>
  <form class="auth-form" (submit)="handleLogin($event)">
    <input type="text" placeholder="Uživatelské jméno" [(ngModel)]="username" name="username" required />
    <input type="password" placeholder="Heslo" [(ngModel)]="password" name="password" required />
    <button type="submit">Přihlásit</button>
    @if (error) { <p class="auth-error">{{ error }}</p> }
  </form>
  <p class="no-account-text">Nemáte účet? <a routerLink="/register">Zaregistrovat se</a></p>
</div>

// src/features/users/Login.jsx
import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import userService from "../../app/services/userService.js";
import "./auth.css";

export default function Login() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");

  const navigate = useNavigate();

  const handleLogin = (e) => {
    e.preventDefault();
    try {
      userService.login({ username, password });
      navigate("/");
      location.reload();
    } catch (err) {
      setError(err.message);
    }
  };

  return (
    <div className="auth-container">
      <h2>Přihlášení</h2>
      <form onSubmit={handleLogin} className="auth-form">
        <input
          type="text"
          placeholder="Uživatelské jméno"
          value={username}
          onChange={(e) => setUsername(e.target.value)}
          required
        />
        <input
          type="password"
          placeholder="Heslo"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
        />
        <button type="submit">Přihlásit</button>
        {error && <p className="auth-error">{error}</p>}
      </form>
      <p className="no-account-text">
        Nemáte účet? <Link to="/register">Zaregistrovat se</Link>
      </p>
    </div>
  );
}
