// src/features/Home.jsx
import { useState, useEffect } from "react";
import Dashboard from "./dashboard/Dashboard";
import projectService from "../app/services/project.service";
import "./home.css";
import { useNavigate } from "react-router-dom";

export default function Home() {
  const [projects, setProjects] = useState([]);
  const [editingId, setEditingId] = useState(null);
  const [editName, setEditName] = useState("");
  const [newProjectName, setNewProjectName] = useState("");
  const [newProjectDescription, setNewProjectDescription] = useState("");
  const [error, setError] = useState("");
  const [filterText, setFilterText] = useState("");

  const navigate = useNavigate();

  // načtení projektů
  useEffect(() => {
    setProjects(projectService.getProjects());
  }, []);

  useEffect(() => {
    if (!error) return;
    const timer = setTimeout(() => setError(""), 5000);
    return () => clearTimeout(timer);
  }, [error]);

  const projectNameExists = (name, ignoreId = null) =>
    projects.some(
      (p) => p.name.toLowerCase() === name.toLowerCase() && p.id !== ignoreId,
    );

  const handleAddProject = (e) => {
    e.preventDefault();
    const trimmedName = newProjectName.trim();
    const trimmedDescription = newProjectDescription.trim();

    if (!trimmedName) {
      setError("Název projektu nesmí být prázdný.");
      return;
    }

    if (projectNameExists(trimmedName)) {
      setError("Projekt s tímto názvem již existuje.");
      return;
    }

    projectService.createProject({
      name: trimmedName,
      description: trimmedDescription,
      ownerId: 1,
    });

    setProjects(projectService.getProjects());
    setNewProjectName("");
    setNewProjectDescription("");
    setError("");
  };

  const handleDelete = (id) => {
    projectService.deleteProject(id);
    setProjects(projectService.getProjects());
  };

  const startEditing = (project) => {
    setEditingId(project.id);
    setEditName(project.name);
  };

  const saveEdit = (id) => {
    const project = projectService.getProjectById(id);
    const trimmedName = editName.trim();

    if (!trimmedName || projectNameExists(trimmedName, id)) {
      setEditingId(null);
      return;
    }

    projectService.updateProject({
      ...project,
      name: trimmedName,
    });

    setProjects(projectService.getProjects());
    setEditingId(null);
  };

  const truncateDescription = (desc) =>
    desc.length > 30 ? desc.slice(0, 30) + "..." : desc;

  // filtrování projektů podle názvu
  const filteredProjects = projects.filter((p) =>
    p.name.toLowerCase().includes(filterText.toLowerCase()),
  );

  return (
    <div className="home-container">
      <h1 className="home-title">Vítejte v Task Manageru</h1>
      <hr />

      <h2 className="home-projects-title" id="home-projects-dashboard-title">
        Dashboard
      </h2>
      <Dashboard projects={projects} />

      <h2 className="home-projects-title">Vaše projekty</h2>

      <div className="project-create-wrap">
        <h3>Vytvořte projekt</h3>
        <form onSubmit={handleAddProject} className="project-create-form">
          <input
            type="text"
            placeholder="Název projektu"
            value={newProjectName}
            onChange={(e) => {
              setNewProjectName(e.target.value);
              if (error) setError("");
            }}
          />
          <textarea
            placeholder="Popis projektu (nepovinné)"
            value={newProjectDescription}
            onChange={(e) => setNewProjectDescription(e.target.value)}
          />
          <button type="submit">Vytvořit</button>
        </form>
        {error && <p className="project-create-error">{error}</p>}
      </div>

      {projects.length > 0 && (
        <div className="project-filter">
          <h3>Vyhledejte konkrétní projekt</h3>
          <input
            type="text"
            placeholder="Filtrovat projekty podle názvu ..."
            value={filterText}
            onChange={(e) => setFilterText(e.target.value)}
          />
        </div>
      )}

      {filteredProjects.length === 0 ? (
        <p className="home-empty">Žádné projekty nenalezeny.</p>
      ) : (
        <div className="home-project-grid">
          {filteredProjects.map((project) => (
            <div
              key={project.id}
              className="project-card"
              style={{ background: project.gradient }}
              onClick={() => {
                if (!editingId) navigate(`/projects/${project.id}`);
              }}
            >
              {editingId === project.id ? (
                <input
                  className="project-name-input"
                  value={editName}
                  onChange={(e) => setEditName(e.target.value)}
                  onBlur={() => saveEdit(project.id)}
                  onKeyDown={(e) => e.key === "Enter" && saveEdit(project.id)}
                  autoFocus
                />
              ) : (
                <>
                  <h3 className="project-name">{project.name}</h3>
                  {project.description && (
                    <p className="project-description">
                      {truncateDescription(project.description)}
                    </p>
                  )}
                </>
              )}
              <p className="project-date">
                Vytvořeno: {new Date(project.createdAt).toLocaleDateString()}
              </p>

              <div className="project-btns">
                <button
                  className="project-edit-btn"
                  onClick={(e) => {
                    e.stopPropagation();
                    startEditing(project);
                  }}
                >
                  <i className="fa-solid fa-pen-to-square"></i>
                </button>
                <button
                  className="project-delete-btn"
                  onClick={(e) => {
                    e.stopPropagation();
                    handleDelete(project.id);
                  }}
                >
                  <i className="fa-solid fa-trash"></i>
                </button>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// bp-angular-app/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { DashboardComponent } from '../dashboard/dashboard.component';
import { ProjectService } from '../../services/project.service';

@Component({
  standalone: true,
  imports: [CommonModule, FormsModule, DashboardComponent],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css',
})
export class HomeComponent implements OnInit {
  projects: any[] = [];
  editingId: number | null = null;
  editName = '';
  newProjectName = '';
  newProjectDescription = '';
  error = '';
  filterText = '';
  deleteModal: any = null;
  confirmName = '';

  constructor(private projectService: ProjectService, private router: Router) {}
  ngOnInit(): void { this.projects = this.projectService.getProjects(); }
  goToProject(id: number) { this.router.navigate(['/projects', id]); }
  handleAddProject(event: Event) { event.preventDefault(); const trimmedName = this.newProjectName.trim(); if (!trimmedName) return (this.error = 'Název projektu nesmí být prázdný.'); if (this.projects.some((p) => p.name.toLowerCase() === trimmedName.toLowerCase())) return (this.error = 'Projekt s tímto názvem již existuje.'); this.projectService.createProject({ name: trimmedName, description: this.newProjectDescription.trim(), ownerId: 1 }); this.projects = this.projectService.getProjects(); this.newProjectName = ''; this.newProjectDescription = ''; this.error = ''; }
  saveEdit(id: number) { const trimmedName = this.editName.trim(); if (!trimmedName) return (this.editingId = null); if (this.projects.some((p) => p.id !== id && p.name.toLowerCase() === trimmedName.toLowerCase())) return (this.editingId = null); const project = this.projectService.getProjectById(id); this.projectService.updateProject({ ...project, name: trimmedName }); this.projects = this.projectService.getProjects(); this.editingId = null; }
  deleteProject() { this.projectService.deleteProject(this.deleteModal.id); this.projects = this.projectService.getProjects(); this.deleteModal = null; this.confirmName = ''; }
  get filteredProjects() { return this.projects.filter((p) => p.name.toLowerCase().includes(this.filterText.toLowerCase())); }
  truncateDescription(desc: string) { return desc?.length > 30 ? `${desc.slice(0, 30)}...` : desc; }
}
